[[headers]]
  for = "/web5/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/web5/*.pck"
  [headers.values]
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/web5/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/web5/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
